apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rural-armadillo-go 
  janus-idp.io/tekton: rural-armadillo-go
  backstage.io/kubernetes-id: rural-armadillo-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: rural-armadillo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  